name: Email Check Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3003446@ds.study.iitm.ac.in
        run: echo "Hello, world!"
